#!/bin/bash
sourc="/root/list_api"
removing="/root/dead_list_api"
cd /root/
#git clone https://privat0x@bitbucket.org/privat0x/l00k.git
#cat /root/l00k/user_done > /root/list_api
rm -rf /root/l00k
#curl -s https://raw.githubusercontent.com/5y5l0g0x7/l00k/master/user_done > /root/list_api
python3 /root/op.py
cat $sourc | wc -l

printf " user ready :"
printf $(cat $sourc | wc -l)
echo -e "\n"
while IFS= read line
do
    printf  $line
	printf  " -----> "
	do_usr=$(echo $line | cut -d "#" -f1)
	do_id=$(echo $line | cut -d "#" -f2)
	do_tk=$(echo $line | cut -d "#" -f3)
	do_nbr=$(echo $line | cut -d "#" -f4)
	#echo $do_id $do_tk $do_usr
	
        #python /root/all/jexboss/jexboss.py -u $line
	stt=$(curl -s -X POST -F token=$do_tk -F ref=master  https://gitlab.com/api/v4/projects/$do_id/trigger/pipeline |  jq '.status')
        if [ $stt == null ]; 
	then 
	printf "dead"
	echo "$do_nbr" >> $removing
	#sed "/^$do_usr/d" -i $sourc
	else
	printf $stt
	fi
	
	
	echo ""

done < $sourc

cd /root/
while IFS= read line
do
	printf  $line
	python3 /root/clean_db.py $line

done < $removing


#rm -rf c0da/
#git clone https://github.com/5y5l0g0x6/l00k.git
#cd /root/l00k
#sed -i "s/github/5y5l0g0x6:yepyepbaba123A*@github/" /root/l00k/.git/config
#cat $sourc >  /root/l00k/user_done
#git config --global user.email 5y5l0g0x6@s00kag3imb.tk
#echo `date` >> time_statu && git add --all && git commit -m "l00000 da v1" && git push origin master
#cd /root/
#rm -rf /root/l00k

